feat: add holesky support, update doc
lidofinance/AVotesParser pull request #8
Opened 2023-10-11 15:06 UTC by BATMAH69

2023-10-12 13:30 UTC, katamarinaki approved these changes
👍

2023-10-12 13:57 UTC, TheDZhon requested changes
Thank you so much :+1:

I'd suggest to remove the deprecated networks to not blow up their list :)

2023-10-12 13:57 UTC, TheDZhon commented on README.md
> +### for development
♥

2023-10-12 13:57 UTC, TheDZhon commented on README.md
> +  --net {mainnet,goerli,holesky,kovan,rinkebay,ropsten}
let's leave only mainnet, goerli and holesky

2023-10-12 18:21 UTC, TheDZhon commented on production/avotes-parser-core/avotes_parser/core/ABI/utilities/etherscan.py
>      'kovan': 'https://api-kovan.etherscan.io',
can remove the deprecated networks :pray:

2023-10-16 06:28 UTC, TheDZhon approved these changes
Let's roll it out

2023-10-16 06:28 UTC, merged